--TABLE-1: Fall22_S003_12_PASSENGER
CREATE TABLE Fall22_S003_12_PASSENGER (
  PID VARCHAR(6) NOT NULL,
  FIRSTNAME VARCHAR(25) NOT NULL,
	LASTNAME VARCHAR(25),
	GENDER CHAR(1) NOT NULL,
	check(GENDER = 'M' OR GENDER = 'F'),
	DOB DATE NOT NULL,
	CONTACTNO NUMBER(10,0) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
  PRIMARY KEY(PID),
  UNIQUE(EMAIL) );
  

--TABLE-2: Fall22_S003_12_DRIVER 
CREATE TABLE Fall22_S003_12_DRIVER (
	DLNO VARCHAR(4) NOT NULL,
	FIRSTNAME VARCHAR(25) NOT NULL,
	LASTNAME VARCHAR(25),
	GENDER CHAR(1) NOT NULL
	check(GENDER = 'M' OR GENDER = 'F'),
	DOB DATE NOT NULL,
	DEMAIL VARCHAR(30) NOT NULL,
	PRIMARY KEY(DLNO),
	UNIQUE(DEMAIL) );


--TABLE-3: Fall22_S003_12_DRIVER_PHONE	
CREATE TABLE Fall22_S003_12_DRIVER_PHONE (
	DLNO VARCHAR(4) NOT NULL,
	PHNO NUMBER(10,0) NOT NULL,
	PRIMARY KEY(DLNO, PHNO),
	FOREIGN KEY(DLNO) references Fall22_S003_12_DRIVER(DLNO)
		on delete cascade );
		

--TABLE-4: Fall22_S003_12_VEHICLE 
CREATE TABLE Fall22_S003_12_VEHICLE (
  VID VARCHAR(5) NOT NULL,
  BRAND VARCHAR(10)  NOT NULL,
  MODEL VARCHAR(10)  NOT NULL,
  COLOUR VARCHAR(10),
  DRVID VARCHAR(4) NOT NULL,
  PRIMARY KEY(VID),
  FOREIGN KEY(DRVID) references Fall22_S003_12_DRIVER(DLNO)
		on delete cascade );
		

--TABLE-5: Fall22_S003_12_PAYMENT 
CREATE TABLE Fall22_S003_12_PAYMENT (
  PAYID VARCHAR(6) NOT NULL,
  CARDNUMBER NUMBER(12,0) NOT NULL,
  EXPIRYDATE DATE NOT NULL,
  PSGID VARCHAR(6) NOT NULL,
  PRIMARY KEY(PAYID),
  FOREIGN KEY(PSGID) references Fall22_S003_12_PASSENGER(PID)
		on delete cascade );

		
--TABLE-6: Fall22_S003_12_BOOKING
CREATE TABLE Fall22_S003_12_BOOKING (
  BID VARCHAR(6) NOT NULL,
  PICKCITY VARCHAR(15) NOT NULL,
  PICKPINCODE NUMBER(5,0) NOT NULL,
  DROPCITY VARCHAR(15) NOT NULL,
  DROPPINCODE NUMBER(5,0) NOT NULL,
  FAREAMOUNT NUMBER(5,0) NOT NULL,
  PAYID VARCHAR(6) NOT NULL,
  PSGID VARCHAR(6) NOT NULL,
  BDATE DATE NOT NULL,
  BTIME DATE NOT NULL,
  NOOFPASSENGERS NUMBER(1) NOT NULL,
  DRVID VARCHAR(4) NOT NULL,
  PRIMARY KEY(BID),
  FOREIGN KEY(DRVID) references Fall22_S003_12_DRIVER(DLNO)
		on delete cascade,
  FOREIGN KEY(PAYID) references Fall22_S003_12_PAYMENT(PAYID)
		on delete cascade,
  FOREIGN KEY(PSGID) references Fall22_S003_12_PASSENGER(PID)
		on delete cascade );


--TABLE-7: Fall22_S003_12_RIDESCHEDULE		
CREATE TABLE Fall22_S003_12_RIDESCHEDULE (
  RIDEID VARCHAR(6) NOT NULL,
  BID VARCHAR(6) NOT NULL,
  STARTTIME TIMESTAMP NOT NULL,
  ENDTIME TIMESTAMP NOT NULL, 
  PRIMARY KEY(RIDEID),
  FOREIGN KEY(BID) references Fall22_S003_12_BOOKING(BID)
		on delete cascade );